Clean arch
go-park-mail-ru/2021_2_LostPointer pull request #13
Opened 2021-10-09 12:18 UTC by VErshovBMSTU

Слава Украине

2021-10-09 13:25 UTC, esuwu commented on internal/models/response.go
> +	Message string `json:"message"`
а точно ли нужно для этого структуру создавать?

2021-10-09 13:25 UTC, esuwu commented on internal/users/delivery/user_handler.go
> +type UserDeliveryRealisation struct {
Не думаю что нужно писать Realisation, звучит странно

2021-10-09 13:25 UTC, esuwu commented on internal/users/delivery/user_handler.go
> +	if len(sessionToken) == 0 {
В каком случае длина токена будет ноль?

2021-10-09 13:48 UTC, 23-yo-designer-from-san-francisco commented on internal/users/delivery/user_handler.go
> +type UserDeliveryRealisation struct {
Я вообще не понял, что в структуре, по ее названию. Realisation это не Implementation

2021-10-09 14:12 UTC, 23-yo-designer-from-san-francisco commented on internal/models/session.go
> +	UserId  uint64
[Правила именования переменных](https://betterprogramming.pub/naming-conventions-in-go-short-but-descriptive-1fa7c6d2f32a#5902)

2021-10-09 14:12 UTC, 23-yo-designer-from-san-francisco commented on internal/models/user.go
> +	NickName     string `json:"nickname,omitempty"`
NickName -> Nickname, отступы

2021-10-09 14:12 UTC, 23-yo-designer-from-san-francisco commented on internal/users/delivery/user_handler.go
> +		Expires:  time.Now().Add(time.Hour * 24 * 30),
Хардкод

2021-10-09 14:12 UTC, 23-yo-designer-from-san-francisco commented on internal/users/repository/user_repository.go
> +type UserRepositoryRealisation struct {
Realisation убрать

2021-10-09 14:12 UTC, 23-yo-designer-from-san-francisco commented on internal/users/repository/user_repository.go
> +func NewUserRepositoryRealization(db *sql.DB, redisConnection *redis.Client) UserRepositoryRealisation {
Смесь британского и американского, убрать Realization

2021-10-09 14:12 UTC, 23-yo-designer-from-san-francisco commented on internal/users/repository/user_repository.go
> +		bytes[i] = byte(RandInt(97, 122))
[Таблица ASCII](https://simple.m.wikipedia.org/wiki/File:ASCII-Table-wide.svg). Желательно добавить цифры и заглавные буквы. Со специальными символами осторожно, поскольку эта функция используется для генерации значений [кук](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#attributes)

2021-10-09 14:12 UTC, 23-yo-designer-from-san-francisco commented on internal/users/repository/user_repository.go
> +	hasher := sha1.New()
[SHA1 для хэширования паролей](https://stackoverflow.com/a/2774744)

2021-10-09 14:12 UTC, 23-yo-designer-from-san-francisco commented on internal/users/repository/user_repository.go
> +	var id uint64 = 0
[Дефолтные значения переменных в Go](https://tour.golang.org/basics/12)

2021-10-09 14:12 UTC, 23-yo-designer-from-san-francisco commented on internal/users/repository/user_repository.go
> +		userData.Email, GetHash(userData.Password + salt), userData.NickName , salt,
Пробел перед запятой =)

2021-10-09 14:12 UTC, 23-yo-designer-from-san-francisco commented on internal/users/usecase.go
> +}
[Нет пустой строки в конце файла](https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log)

2021-10-09 14:12 UTC, 23-yo-designer-from-san-francisco commented on internal/users/usecase/user_usecase.go
> +	userDB   		users.UserRepository
Странный огромный отступ

2021-10-09 14:12 UTC, 23-yo-designer-from-san-francisco commented on internal/users/usecase/user_usecase.go
> +		`[\@\ \!\"\#\$\%\&\'\(\)\*\+\,\-\.\/\:\;\<\=\>\?\?\[\\\]\^\_]`: "Password must contain as least one special symbol",
special (symbol -> character)

2021-10-09 14:12 UTC, 23-yo-designer-from-san-francisco commented on internal/users/usecase/user_usecase.go
> +		return false, "The length of the name must be from 2 to 15 characters and must not contain spaces," +
в Regex задано 3, тут написано 2. Минимальную и максимальную длину надо вынести в константы во избежание подобных ситуаций

2021-10-09 14:12 UTC, 23-yo-designer-from-san-francisco commented on main.go
>  		DB:       1,
Стоит вынести в константы

2021-10-09 14:12 UTC, 23-yo-designer-from-san-francisco commented on main.go
> +}
Нет новой строки

2021-10-09 14:23 UTC, VErshovBMSTU commented on internal/users/delivery/user_handler.go
> +	if len(sessionToken) == 0 {
В случае ошибки, например, после проверки на уникальность почты или никнейма, оказывается, что данные не уникальных => мы не можем зарегистрировать пользователя => токен не создастся, поэтому вернется пустая строка. Как более лаконично имплементировать эту логику я не знаю.

2021-10-10 21:06 UTC, saptded commented on internal/models/session.go
> +	UserId  uint64
![image](https://user-images.githubusercontent.com/74863449/136712951-7e107a5d-16d0-4ad2-9488-d3c1faad93cc.png)
нихуя ошибка 1020

2021-10-11 21:36 UTC, 23-yo-designer-from-san-francisco commented on pkg/users/repository.go
> +	UserExits(models.Auth) (uint64, error)
Все-таки DoesUserExist, тем более не Exi**ts**

2021-10-11 21:36 UTC, 23-yo-designer-from-san-francisco commented on pkg/users/repository/user_repository_test.go
> +		expected 	uint64
отступ =( В других тестах то же самое

2021-10-11 21:36 UTC, 23-yo-designer-from-san-francisco commented on pkg/users/repository/user_repository_test.go
> +	tests := []struct {
Во всех тестах используются одинаковые данные, можно было вынести их в const. В других тестах то же самое

2021-10-11 21:36 UTC, 23-yo-designer-from-san-francisco commented on pkg/users/repository/user_repository_test.go
> +	for _, tt := range tests {
`tt` это же `testCase`? Возможно неудачное название, приходится думать

2021-10-11 21:36 UTC, 23-yo-designer-from-san-francisco commented on pkg/users/repository/user_repository_test.go
> +	expected := "b603de426ed0b347d8ca096fb13ba40057d1cb21c9767f231cbb490f09fee088"
Тест ради теста, конечно; выглядит максимально странно, но писать `expected := GetHash(inputStr)` было бы еще более странно

2021-10-11 21:36 UTC, 23-yo-designer-from-san-francisco commented on pkg/users/repository/user_repository_test.go
> +func TestGetRandomString(t *testing.T) {
По идее можно прогнать несколько раз и убедиться в том, что она выдает действительно разные значения

2021-10-11 21:36 UTC, 23-yo-designer-from-san-francisco commented on pkg/users/repository/user_repository_test.go
> +func TestNewUserRepository(t *testing.T) {
смешной тест

2021-10-11 21:36 UTC, 23-yo-designer-from-san-francisco commented on pkg/users/usecase/user_usecase.go
> +}
нет новой строки

2021-10-11 21:36 UTC, 23-yo-designer-from-san-francisco commented on pkg/users/usecase/user_usecase_test.go
> +			name: "UserExist error",
exists

2021-10-11 21:36 UTC, 23-yo-designer-from-san-francisco commented on pkg/users/usecase/user_usecase_test.go
> +				message: "Password must contain at least one uppercase letter",
Можно было подтянуть текст ошибки из констант в соответствующем файле, чтобы потом не переписывать тесты в случае изменения текста ошибки

2021-10-11 21:36 UTC, 23-yo-designer-from-san-francisco commented on pkg/users/usecase/user_usecase_test.go
> +				message: "The length of nickname must be from 3 to 15 characters",
Тут особенно важно текст ошибки подцеплять извне, чтобы не ломались тесты, т.к. количество символов точно может поменяться

2021-10-22 11:55 UTC, 23-yo-designer-from-san-francisco commented on internal/artist/delivery/artist_handler.go
> +			Status:  400,
Заменить магическое число на константу из `http`

2021-10-22 11:55 UTC, 23-yo-designer-from-san-francisco commented on internal/artist/repository/artist_repository_test.go
> +					"LEFT JOIN albums alb ON alb.id = t.album " +
Почему везде именно LEFT JOIN?

2021-10-22 11:55 UTC, 23-yo-designer-from-san-francisco commented on internal/music/repository/music_repository_test.go
> +				for i := 0; i < 1; i++ {
Зачем цикл, который выполняется 1 раз?

2021-10-22 11:55 UTC, 23-yo-designer-from-san-francisco commented on internal/users/delivery/user_handler_test.go
> +			expectedJSON: "{\"status\":401,\"message\":\"User is not authorized\"}\n",
Можно было попробовать сделать через обратные кавычки [ссылка](https://yourbasic.org/golang/multiline-string/#raw-string-literals)

2021-10-22 11:55 UTC, 23-yo-designer-from-san-francisco commented on internal/users/delivery/user_handler_test.go
> +			expectedJSON: "{\"status\":400,\"message\":\"BadRequest\"}\n",
Почему `\n`?

2021-10-22 11:55 UTC, 23-yo-designer-from-san-francisco commented on internal/users/repository/user_repository.go
> +			return 0, &models.CustomError{ErrorType: 401}  // status 401
Лучше было взять из `http`

2021-10-22 11:55 UTC, 23-yo-designer-from-san-francisco commented on internal/users/usecase/user_usecase_test.go
>  				Email: "alexeikosenko@gmail.com",
алексей `косенко`

2021-10-22 11:55 UTC, 23-yo-designer-from-san-francisco commented on internal/users/usecase/user_usecase_test.go
>  		// ----------EMAIL----------
Да мы заметили

2021-10-30 12:09 UTC, esuwu requested changes

2021-10-30 12:09 UTC, esuwu commented on cmd/main.go
> +const redisDB = 1
странное название константы

2021-10-30 12:09 UTC, esuwu commented on internal/album/delivery/album_handler.go
> +const NoArtists = "No albums"
No artists = No albums?

2021-10-30 12:09 UTC, esuwu commented on internal/album/repository/album_repository.go
> +	rows, err := albumRepository.Database.Query("SELECT a.id, a.title, a.year, art.name, "+
лучше одинарные кавычки

2021-10-30 12:09 UTC, esuwu commented on internal/album/repository/album_repository.go
> +	var album models.Album
эта переменная использутеся только внутри цикла, лучше ее как раз там создавать

2021-10-30 12:09 UTC, esuwu commented on internal/album/usecase/album_usecase.go
> +const DatabaseNotResponding = "Database not responding"
все вот эти строки можно вынести в отдельный файл errors внутри каждой модели, либо в общий пакет errors

2021-10-30 12:09 UTC, esuwu commented on internal/artist/repository/artist_repository.go
> +			track.File = ""
что-то странное. track.File по дефолту пустой должен же быть

2021-10-30 12:09 UTC, esuwu commented on internal/middleware/middleware.go
> +			log.Println(tokenReq)
зачем печатать токен в консоль вывода?

2021-10-30 12:09 UTC, esuwu commented on internal/playlist/repository.go
> +	Get(amount int, id int) ([]models.Playlist, error)
название функции лучше поменять. Не очень понятно по ней что она делает

2021-10-30 12:09 UTC, esuwu commented on internal/queue/repository.go
> +package queue
зачем нужны пустые файлы?

2021-10-30 12:09 UTC, esuwu commented on internal/users/repository/user_repository.go
> +	var password, salt string
``` 
var (
  id uint64
  password, salt string
)
```

2021-10-30 12:09 UTC, esuwu commented on internal/users/repository/user_repository.go
> +	settings.BigAvatar = os.Getenv("ROOT_PATH_PREFIX") + avatarFilename + "_500px.webp"
500px.webp, 150px.webp лучше в константы

2021-10-30 12:09 UTC, esuwu commented on internal/users/repository/user_repository.go
> +	out, err = os.Create(os.Getenv("FULL_PATH_PREFIX") + fileName + "_150px.webp")
аналогично

2021-10-30 12:09 UTC, esuwu commented on internal/users/repository/user_repository.go
> +	out, err := os.Create(os.Getenv("FULL_PATH_PREFIX") + fileName + "_500px.webp")
аналогично

2021-10-30 12:09 UTC, esuwu commented on internal/users/repository/user_repository.go
> +		err := os.Remove(filename + "_150px.webp")
также

2021-10-30 12:09 UTC, esuwu commented on internal/users/repository/user_repository.go
> +		err = os.Remove(filename + "_500px.webp")
также

2021-10-30 12:09 UTC, esuwu commented on internal/users/usecase/user_usecase.go
> +const PasswordValidationInvalidLengthMessage = "Password must contain at least " + passwordRequiredLength + " characters"
вот эти константы можно в errors пакет или в constants в этой модели

2021-10-30 17:52 UTC, saptded commented on internal/album/delivery/album_handler.go
> +const NoArtists = "No albums"
да

2021-10-30 17:53 UTC, VErshovBMSTU commented on internal/album/delivery/album_handler.go
> +const NoArtists = "No albums"
Леха здаров)

2021-10-31 21:17 UTC, closed without merging