Los 52
go-park-mail-ru/2021_2_LostPointer pull request #14
Opened 2021-10-29 21:56 UTC by saptded

2021-10-29 23:05 UTC, 23-yo-designer-from-san-francisco commented on internal/artist/repository/artist_repository.go
> +	//"ORDER BY t.listen_count LIMIT $2", id, amount)
Удали, если не нужно. Не надо гадить в репу

2021-10-29 23:09 UTC, 23-yo-designer-from-san-francisco requested changes

2021-10-29 23:09 UTC, 23-yo-designer-from-san-francisco commented on internal/users/repository/user_repository.go
> +}
Зачем?

2021-10-29 23:09 UTC, 23-yo-designer-from-san-francisco commented on internal/users/repository/user_repository.go
> +}
Новая строка + сомнительно. Зачем, если имя файла генерируется для фотки заново?

2021-10-29 23:09 UTC, 23-yo-designer-from-san-francisco commented on internal/users/repository/user_repository.go
> +	sanitizedData.Password = sanitize.HTML(userData.Password)
Не надо

2021-10-30 11:52 UTC, esuwu requested changes

2021-10-30 11:52 UTC, esuwu commented on internal/artist/repository/artist_repository.go
> +	trackRows, err := artistRepository.Database.Query("SELECT tracks.id, tracks.title, explicit, "+
Вместо складывание строк можно использовать одинарчные кавычки с переносом строк

2021-10-30 11:52 UTC, esuwu commented on internal/models/track.go
> +	//Album       string `json:"album,omitempty"`
ненужный комментарий

2021-10-31 07:48 UTC, merged